name: Publish Latest Docker image
on:
  workflow_dispatch:
  push:
    branches:
      - "main"
  schedule:
    - cron: '0 0 * * 0'
jobs:
  push_to_registry:
    environment: docker_build
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      - name: Get current date
        id: date
        run: echo "TAG=$(date +'%Y%m%dT%H%M%S')" >> $GITHUB_ENV
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          tags: |
            ghcr.io/eifoen/docker-texlive:latest
            ghcr.io/eifoen/docker-texlive:${{ env.TAG }}
          push: true
